# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f048f64dff89a41b63bacbeac0a7811ceb0e5e352ab2cd220b2fc37a85fa4af432a8206cf577f4b5dd05d90b5d07b18a386be21e5b144575d0e0c16cedb1b84

test:
  secret_key_base: 5efcd3c2e8795f211556c9636f7654966a6009c51001a7439164a7fa390626719402908f315038e44bd123689a571c80ff0bbf5915f383fd25419afeb04f7499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
